'use client';

import { useEffect, useState } from 'react';

type Category = { id: string; name: string };
type Service = { id: string; categoryId: string; slug: string; title: string; shortDescription: string | null; badge: string | null; status: 'DRAFT' | 'PUBLISHED' | 'ARCHIVED'; sortOrder: number; category: Category; _count: { priceItems: number; leads: number } };
const blank = (categoryId = '') => ({ categoryId, slug: '', title: '', shortDescription: null as string | null, badge: null as string | null, status: 'DRAFT' as const, sortOrder: 0 });

export default function AdminServicesPage() {
  const [services, setServices] = useState<Service[]>([]);
  const [categories, setCategories] = useState<Category[]>([]);
  const [draft, setDraft] = useState<Service | null>(null);
  const [creating, setCreating] = useState(false);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState('');
  const load = async () => { try { const response = await fetch('/api/admin/services'); const data = await response.json(); if (!response.ok) throw new Error(); setServices(data.services); setCategories(data.categories); } catch { setMessage('Không thể tải dịch vụ.'); } finally { setLoading(false); } };
  // The initial request synchronizes this client view with the protected server resource.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, []);
  const save = async () => { if (!draft) return; setSaving(true); setMessage(''); const url = creating ? '/api/admin/services' : `/api/admin/services/${draft.id}`; const response = await fetch(url, { method: creating ? 'POST' : 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ categoryId: draft.categoryId, slug: draft.slug, title: draft.title, shortDescription: draft.shortDescription || null, badge: draft.badge || null, status: draft.status, sortOrder: Number(draft.sortOrder) }) }); const data = await response.json(); setSaving(false); if (!response.ok) { setMessage(data.error || 'Không thể lưu dịch vụ.'); return; } setMessage('Đã lưu vào cơ sở dữ liệu.'); setDraft(null); setCreating(false); await load(); };
  if (loading) return <main className="p-6">Đang tải dịch vụ…</main>;
  return <main className="p-6 space-y-5"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold">Dịch vụ</h1><p className="text-sm text-text-muted">Dịch vụ được lưu trong PostgreSQL.</p></div><button className="rounded-ctrl bg-primary px-4 py-2 text-sm font-bold text-white" onClick={() => { setDraft({ id: '', ...blank(categories[0]?.id), category: categories[0] ?? { id: '', name: '' }, _count: { priceItems: 0, leads: 0 } }); setCreating(true); }}>Tạo dịch vụ</button></div>{message && <p role="status" className="text-sm text-primary">{message}</p>}{draft && <section className="space-y-3 rounded-card border bg-white p-4"><h2 className="font-bold">{creating ? 'Tạo dịch vụ' : 'Chỉnh sửa dịch vụ'}</h2><input className="w-full rounded border p-2" value={draft.title} placeholder="Tên dịch vụ" onChange={e => setDraft({ ...draft, title: e.target.value })}/><input className="w-full rounded border p-2" value={draft.slug} placeholder="slug-an-toan" onChange={e => setDraft({ ...draft, slug: e.target.value })}/><select className="w-full rounded border p-2" value={draft.categoryId} onChange={e => setDraft({ ...draft, categoryId: e.target.value })}>{categories.map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select><input className="w-full rounded border p-2" value={draft.badge ?? ''} placeholder="Nhãn" onChange={e => setDraft({ ...draft, badge: e.target.value || null })}/><textarea className="w-full rounded border p-2" value={draft.shortDescription ?? ''} placeholder="Mô tả ngắn" onChange={e => setDraft({ ...draft, shortDescription: e.target.value || null })}/><div className="flex gap-3"><select className="rounded border p-2" value={draft.status} onChange={e => setDraft({ ...draft, status: e.target.value as Service['status'] })}><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option><option value="ARCHIVED">Archived</option></select><input className="w-24 rounded border p-2" type="number" min="0" value={draft.sortOrder} onChange={e => setDraft({ ...draft, sortOrder: Number(e.target.value) })}/><button disabled={saving} className="rounded-ctrl bg-primary px-4 py-2 text-sm font-bold text-white" onClick={() => void save()}>{saving ? 'Đang lưu…' : 'Lưu'}</button><button className="px-3" onClick={() => { setDraft(null); setCreating(false); }}>Hủy</button></div></section>}<section className="overflow-hidden rounded-card border bg-white"><div className="divide-y">{services.map(service => <div key={service.id} className="flex items-center justify-between gap-4 p-4"><div><p className="font-bold">{service.title}</p><p className="text-xs text-text-muted">/{service.slug} · {service.category.name} · {service.status} · {service._count.priceItems} giá · {service._count.leads} lead</p></div><button className="rounded border px-3 py-1 text-sm" onClick={() => { setDraft(service); setCreating(false); }}>Sửa</button></div>)}</div></section></main>;
}
