'use client';

import React from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { useSiteConfig } from '@/components/SiteConfigProvider';

export const Footer: React.FC = () => {
  const config = useSiteConfig();
  if (!config) return <footer className="border-t border-gray-200 bg-surface-secondary px-4 py-12 text-center text-sm text-text-muted"><p role="status">Thông tin liên hệ tạm thời chưa khả dụng.</p></footer>;

  return <footer className="border-t border-gray-200 bg-surface-secondary pb-20 pt-12 text-sm text-text-main md:pb-12"><div className="mx-auto max-w-7xl px-4 sm:px-6"><div className="grid grid-cols-1 gap-8 md:grid-cols-4">
    <div className="space-y-3"><div className="flex items-center gap-2"><div className="relative h-10 w-10"><Image src="/logo-web.png" alt={config.brandName} fill className="object-contain" /></div><span className="text-xl font-black text-primary">{config.brandName}</span></div><p className="text-xs leading-relaxed text-text-muted">{config.slogan}</p><div className="border-t border-gray-200 pt-2 text-xs text-text-muted"><p><strong>Mã số thuế:</strong> {config.businessCode}</p><p><strong>Thời gian làm việc:</strong> {config.workingHours}</p></div></div>
    <div><h4 className="mb-3 text-xs font-bold uppercase tracking-wider">Dịch Vụ Chính</h4><ul className="space-y-2 text-xs text-text-muted"><li><Link href="/ve-sinh-nha-cua" className="hover:text-primary">Tổng vệ sinh nhà cửa</Link></li><li><Link href="/dich-vu" className="hover:text-primary">Danh mục dịch vụ</Link></li><li><Link href="/ve-sinh-sau-xay-dung" className="hover:text-primary">Vệ sinh sau xây dựng</Link></li><li><Link href="/ve-sinh-van-phong" className="hover:text-primary">Vệ sinh văn phòng</Link></li><li><Link href="/giat-ghe-sofa" className="hover:text-primary">Giặt ghế sofa & Nệm</Link></li><li><Link href="/dich-vu-lau-kinh" className="hover:text-primary">Dịch vụ lau kính tòa nhà</Link></li><li><Link href="/ve-sinh-san-pickleball" className="hover:text-primary">Vệ sinh sân Pickleball</Link></li></ul></div>
    <div><h4 className="mb-3 text-xs font-bold uppercase tracking-wider">Trạm Phục Vụ Hà Nội</h4><ul className="space-y-1.5 text-xs text-text-muted"><li><strong>Trụ sở chính:</strong> {config.mainAddress}</li>{config.branchAddresses.map((branch, index) => <li key={branch}><strong>Trạm {index + 1}:</strong> {branch}</li>)}</ul></div>
    <div><h4 className="mb-3 text-xs font-bold uppercase tracking-wider">Liên Hệ & Cam Kết</h4><div className="space-y-2 text-xs text-text-muted"><p><strong>Hotline 24/7:</strong> <a href={`tel:${config.hotlines[0].replace(/\./g, '')}`} className="font-bold text-primary hover:underline">{config.hotlines[0]}</a> - <a href={`tel:${config.hotlines[1].replace(/\./g, '')}`} className="font-bold text-primary hover:underline">{config.hotlines[1]}</a></p><p><strong>Email:</strong> {config.emails[0]}</p><div className="mt-3 rounded-lg border border-primary/20 bg-primary-soft/50 p-3"><p className="text-[11px] font-semibold text-primary">CAM KẾT {config.brandName.toUpperCase()}:</p><p className="mt-1 text-[11px] text-text-muted">{config.footerCommitment}</p></div></div></div>
  </div><div className="mt-8 flex flex-col items-center justify-between gap-2 border-t border-gray-200 pt-6 text-center text-xs text-text-muted sm:flex-row"><p>© 2026 {config.brandName}. All rights reserved. Tiêu chuẩn Structured Clean.</p><div className="flex gap-4"><Link href="/chinh-sach-bao-mat" className="hover:text-primary">Chính sách bảo mật</Link><Link href="/chinh-sach-bao-hanh" className="hover:text-primary">Chính sách bảo hành</Link></div></div></div></footer>;
};
